/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AdrianComponent {
    }
    interface AnmeldeformularComponent {
        "titel": string;
    }
    interface FlipCard {
        "Picture1": string;
        "Picture2": string;
        "Picture3": string;
        "cardescriptionone": string;
        "cardescriptionthree": string;
        "cardescriptiontwo": string;
        "carnameone": string;
        "carnamethree": string;
        "carnametwo": string;
        "plz": string;
    }
    interface HeaderLn {
    }
    interface JonaComponent {
        "slHeroHeadline": string;
    }
    interface JuliaComponent {
        "titel": string;
    }
    interface MellyComponent {
        "img1": string;
        "img2": string;
        "img3": string;
        "img4": string;
        "img5": string;
    }
    interface MorizComponent {
        "city": string;
        "imageFacebook": string;
        "imageInstagram": string;
        "imageLinkedIn": string;
        "imageMastercard": string;
        "imagePayPal": string;
        "imageTwitter": string;
        "imageVisa": string;
        "imageWhatsapp": string;
        "imageXing": string;
        "imageYouTube": string;
        "plz": string;
        "siteone": string;
        "sites": string;
        "sitethree": string;
        "sitetwo": string;
        "socialMedia": any;
        "street": string;
        "urlone": string;
        "urlthree": string;
        "urltwo": string;
    }
    interface MorizCompronent2 {
        "street": string;
    }
}
declare global {
    interface HTMLAdrianComponentElement extends Components.AdrianComponent, HTMLStencilElement {
    }
    var HTMLAdrianComponentElement: {
        prototype: HTMLAdrianComponentElement;
        new (): HTMLAdrianComponentElement;
    };
    interface HTMLAnmeldeformularComponentElement extends Components.AnmeldeformularComponent, HTMLStencilElement {
    }
    var HTMLAnmeldeformularComponentElement: {
        prototype: HTMLAnmeldeformularComponentElement;
        new (): HTMLAnmeldeformularComponentElement;
    };
    interface HTMLFlipCardElement extends Components.FlipCard, HTMLStencilElement {
    }
    var HTMLFlipCardElement: {
        prototype: HTMLFlipCardElement;
        new (): HTMLFlipCardElement;
    };
    interface HTMLHeaderLnElement extends Components.HeaderLn, HTMLStencilElement {
    }
    var HTMLHeaderLnElement: {
        prototype: HTMLHeaderLnElement;
        new (): HTMLHeaderLnElement;
    };
    interface HTMLJonaComponentElement extends Components.JonaComponent, HTMLStencilElement {
    }
    var HTMLJonaComponentElement: {
        prototype: HTMLJonaComponentElement;
        new (): HTMLJonaComponentElement;
    };
    interface HTMLJuliaComponentElement extends Components.JuliaComponent, HTMLStencilElement {
    }
    var HTMLJuliaComponentElement: {
        prototype: HTMLJuliaComponentElement;
        new (): HTMLJuliaComponentElement;
    };
    interface HTMLMellyComponentElement extends Components.MellyComponent, HTMLStencilElement {
    }
    var HTMLMellyComponentElement: {
        prototype: HTMLMellyComponentElement;
        new (): HTMLMellyComponentElement;
    };
    interface HTMLMorizComponentElement extends Components.MorizComponent, HTMLStencilElement {
    }
    var HTMLMorizComponentElement: {
        prototype: HTMLMorizComponentElement;
        new (): HTMLMorizComponentElement;
    };
    interface HTMLMorizCompronent2Element extends Components.MorizCompronent2, HTMLStencilElement {
    }
    var HTMLMorizCompronent2Element: {
        prototype: HTMLMorizCompronent2Element;
        new (): HTMLMorizCompronent2Element;
    };
    interface HTMLElementTagNameMap {
        "adrian-component": HTMLAdrianComponentElement;
        "anmeldeformular-component": HTMLAnmeldeformularComponentElement;
        "flip-card": HTMLFlipCardElement;
        "header-ln": HTMLHeaderLnElement;
        "jona-component": HTMLJonaComponentElement;
        "julia-component": HTMLJuliaComponentElement;
        "melly-component": HTMLMellyComponentElement;
        "moriz-component": HTMLMorizComponentElement;
        "moriz-compronent2": HTMLMorizCompronent2Element;
    }
}
declare namespace LocalJSX {
    interface AdrianComponent {
    }
    interface AnmeldeformularComponent {
        "titel"?: string;
    }
    interface FlipCard {
        "Picture1"?: string;
        "Picture2"?: string;
        "Picture3"?: string;
        "cardescriptionone"?: string;
        "cardescriptionthree"?: string;
        "cardescriptiontwo"?: string;
        "carnameone"?: string;
        "carnamethree"?: string;
        "carnametwo"?: string;
        "plz"?: string;
    }
    interface HeaderLn {
    }
    interface JonaComponent {
        "slHeroHeadline"?: string;
    }
    interface JuliaComponent {
        "titel"?: string;
    }
    interface MellyComponent {
        "img1"?: string;
        "img2"?: string;
        "img3"?: string;
        "img4"?: string;
        "img5"?: string;
    }
    interface MorizComponent {
        "city"?: string;
        "imageFacebook"?: string;
        "imageInstagram"?: string;
        "imageLinkedIn"?: string;
        "imageMastercard"?: string;
        "imagePayPal"?: string;
        "imageTwitter"?: string;
        "imageVisa"?: string;
        "imageWhatsapp"?: string;
        "imageXing"?: string;
        "imageYouTube"?: string;
        "plz"?: string;
        "siteone"?: string;
        "sites"?: string;
        "sitethree"?: string;
        "sitetwo"?: string;
        "socialMedia"?: any;
        "street"?: string;
        "urlone"?: string;
        "urlthree"?: string;
        "urltwo"?: string;
    }
    interface MorizCompronent2 {
        "street"?: string;
    }
    interface IntrinsicElements {
        "adrian-component": AdrianComponent;
        "anmeldeformular-component": AnmeldeformularComponent;
        "flip-card": FlipCard;
        "header-ln": HeaderLn;
        "jona-component": JonaComponent;
        "julia-component": JuliaComponent;
        "melly-component": MellyComponent;
        "moriz-component": MorizComponent;
        "moriz-compronent2": MorizCompronent2;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "adrian-component": LocalJSX.AdrianComponent & JSXBase.HTMLAttributes<HTMLAdrianComponentElement>;
            "anmeldeformular-component": LocalJSX.AnmeldeformularComponent & JSXBase.HTMLAttributes<HTMLAnmeldeformularComponentElement>;
            "flip-card": LocalJSX.FlipCard & JSXBase.HTMLAttributes<HTMLFlipCardElement>;
            "header-ln": LocalJSX.HeaderLn & JSXBase.HTMLAttributes<HTMLHeaderLnElement>;
            "jona-component": LocalJSX.JonaComponent & JSXBase.HTMLAttributes<HTMLJonaComponentElement>;
            "julia-component": LocalJSX.JuliaComponent & JSXBase.HTMLAttributes<HTMLJuliaComponentElement>;
            "melly-component": LocalJSX.MellyComponent & JSXBase.HTMLAttributes<HTMLMellyComponentElement>;
            "moriz-component": LocalJSX.MorizComponent & JSXBase.HTMLAttributes<HTMLMorizComponentElement>;
            "moriz-compronent2": LocalJSX.MorizCompronent2 & JSXBase.HTMLAttributes<HTMLMorizCompronent2Element>;
        }
    }
}
